name = "mojo-claim-worker"
main = "worker.js"
compatibility_date = "2024-03-02"

workers_dev = false  # Disable workers.dev subdomain
routes = ["mojoclaim.producerprotocol.pro/*"]  # Bind to your domain

[vars]
THIRDWEB_CLIENT_ID = "your-client-id"
THIRDWEB_SECRET_KEY = "your-secret-key"
