name = "mojo-claim-worker"
main = "worker/index.js"
compatibility_date = "2024-03-06" 
[build]
external = ["thirdweb", "thirdweb/chains"]
[[kv_namespaces]]
binding = "mojo"
id = "16b139517ac346fb9e9a49ea69875723"

[[kv_namespaces]]
binding = "allowlist"
id = "db9c0c1f1526469490e6ffe4f7a417c9"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[r2_buckets]]
binding = local_allowlist"
bucket_name = "<bucketomojo>"


[vars]
THIRDWEB_CLIENT_ID = "${env.THIRDWEB_CLIENT_ID}"